### ISSUE TITLE
flask_restplus and flask_injector do not work together :(

### ISSUE THREAD

**Issue by mtrofimm** [alecthomas/flask_injector#13]
I tried to use your library in my project together with flask_restplus.
There is an issue with handling swagger console.
Given the simple code:

```python
from flask import Flask
from flask_restplus import Api, Resource
from flask_injector import FlaskInjector
import injector

app = Flask(__name__)
api = Api(app)

class ToInject(object):
    def __init__(self, name):
        self.name=name

@api.route('/hello')
class Hello(Resource):
    @injector.inject(name=ToInject('Tom'))
    def __init__(self, name):
        self.name = name

    def get(self):
        return 'Hello {}'.format(self.name);


FlaskInjector(app)

if __name__ == '__main__':
    app.run(debug=True)
```

if u get http://localhost:5000/swagger.json you receive::
injector.CallError: Call to SwaggerView.__init__() failed: __init__() missing 1 required positional argument: 'api' (injection stack: [])

**Comment by jstasiak** [comment]
Hello @mtrofimm, would you mind providing the full stacktrace?

**Comment by mtrofimm** [comment]
sure. I noticed that there is the same stacktrace after http://localhost:5000/hello request :(

```
127.0.0.1 - - [03/Nov/2015 00:46:23] "GET /swagger.json? HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.3/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.3/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python3.3/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/usr/lib/python3.3/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.3/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.3/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.3/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.3/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/usr/lib/python3.3/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.3/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.3/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.3/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.3/site-packages/flask_injector.py", line 133, in wrapper
    resp = original_fun(*args, **kwargs)
  File "/usr/lib/python3.3/site-packages/flask_injector.py", line 72, in view
    self = injector.create_object(cls, additional_kwargs=class_kwargs)
  File "/usr/lib/python3.3/site-packages/injector.py", line 709, in create_object
    (), additional_kwargs, e, self._stack,)
  File "/usr/lib/python3.3/site-packages/injector.py", line 70, in reraise
    raise exception.with_traceback(tb)
  File "/usr/lib/python3.3/site-packages/injector.py", line 702, in create_object
    instance.__init__(**additional_kwargs)
injector.CallError: Call to SwaggerView.__init__() failed: __init__() missing 1 required positional argument: 'api' (injection stack: [])
```

**Comment by jstasiak** [comment]
@mtrofimm Please see https://github.com/alecthomas/flask_injector/commit/91a11254f67ac14ea935fa350c94cbe15df8ed25, it's now in the master branch. Can you test this version?

BTW, it's unrelated but your sample code is a bit off. I let myself correct it:

```python
class ToInject(object):
    def __init__(self, name):
        self.name=name

@api.route('/hello')
class Hello(Resource):
    @injector.inject(name=ToInject)  # <----- changed this line
    def __init__(self, name):
        self.name = name

    def get(self):
        return 'Hello {}'.format(self.name);
```

Note: since ``ToInject`` requires an argument in its constructor you need to create a provider for it and create an instance yourself (or make ``ToInject``'s constructor argument injectable).
