### ISSUE TITLE
Cannot inject dependency when using decorators with view functions.

### ISSUE THREAD

**Issue by sherubthakur** [alecthomas/flask_injector#25]
I was trying to use a decorator in my view function but seems like Flask-Injector cannot inject dependencies when we use a decorator.

Here is the diff of the test case:
```
diff --git i/flask_injector_tests.py w/flask_injector_tests.py
index a038b38..8593841 100644
--- i/flask_injector_tests.py
+++ w/flask_injector_tests.py
@@ -28,7 +28,16 @@ def test_injections():

     app = Flask(__name__)

+    # create a decorator
+    def appender(append = ' says'):
+        def decorator(func):
+            def wrapper(*args, **kwargs):
+                return func(*args, **kwargs) + append
+            return wrapper
+        return decorator
+
     @app.route('/view1')
+    @appender()
     def view1(content: str):
         inc()
         return render_template_string(content)
@@ -71,7 +80,7 @@ def test_injections():

     with app.test_client() as c:
         response = c.get('/view1')
-        eq_(response.get_data(as_text=True), "something")
+        eq_(response.get_data(as_text=True), "something says")

     with app.test_client() as c:
         response = c.get('/view2')
```

Which then fails with the following error.

```
F............
======================================================================
FAIL: flask_injector_tests.test_injections
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sherub/Documents/shuttl/experiments/flask_injector/venv/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/sherub/Documents/shuttl/experiments/flask_injector/flask_injector_tests.py", line 83, in test_injections
    eq_(response.get_data(as_text=True), "something says")
AssertionError: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>\n' != 'something says'
-------------------- >> begin captured logging << --------------------
flask.app: ERROR: Exception on /view1 [GET]
Traceback (most recent call last):
  File "/Users/sherub/Documents/shuttl/experiments/flask_injector/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sherub/Documents/shuttl/experiments/flask_injector/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sherub/Documents/shuttl/experiments/flask_injector/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sherub/Documents/shuttl/experiments/flask_injector/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/sherub/Documents/shuttl/experiments/flask_injector/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sherub/Documents/shuttl/experiments/flask_injector/venv/lib/python3.6/site-packages/Flask-1.0.2-py3.6.egg/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sherub/Documents/shuttl/experiments/flask_injector/flask_injector_tests.py", line 35, in wrapper
    return func(*args, **kwargs) + append
TypeError: view1() missing 1 required positional argument: 'content'
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 13 tests in 0.541s

FAILED (failures=1)
```

**Comment by sherubthakur** [comment]
ok so if I use `functools.wrap` this is no longer a problem. https://docs.python.org/3/library/functools.html#functools.wraps.

Closing the issue.
