### ISSUE TITLE
Support for flask rebar

### ISSUE THREAD

**Issue by Sytten** [alecthomas/flask_injector#33]
I was wondering if it would be complex to support flask-rebar (https://github.com/plangrid/flask-rebar). Basically:
```
Traceback (most recent call last):
  File "/Users//****//Projects//****//Core/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users//****//Projects//****//Core/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/****/Projects/****/Core/venv/lib/python3.7/site-packages/flask_rebar/rebar.py", line 127, in wrapped
    rv = f(*args, **kwargs)
TypeError: auth_callback() missing 1 required positional argument: 'service'
```

**Comment by jstasiak** [comment]
Can you post a code sample to reproduce this? It should work out of the box (just tested it).

**Comment by Sytten** [comment]
```python
from flask import Flask
from injector import Module, provider, singleton

from .auth import AuthService

class ServicesModule(Module):
    @provider
    @singleton
    def provide_auth_service(self, app: Flask) -> AuthService:
        return AuthService()
```
```python
class AuthService:
   def __init__():
        pass
```
```python
from injector import inject

from app.app import registry
from app.services.auth import AuthService

@registry.handles(
    rule="/oauth/callback", method="GET"
)
@inject
def auth_callback(service: AuthService):
    pass
```

Ho thats great news, then it's most likely an import order problem. The code above is just a sample from my codebase, I will retry it again.

**Comment by jstasiak** [comment]
Swap those two lines and you're good :)

```python
    FlaskInjector(app=app, modules=[ServicesModule])

    rebar.init_app(app)
```

PS. Decorating views, handlers etc. with `@inject` is not necessary.

**Comment by Sytten** [comment]
Nice! I will try it asap <3

**Comment by jstasiak** [comment]
Cool! For reference, it has to be done like this because `FlaskInjector` instantiation looks at Flask application's views, handlers etc. present at the time, it doesn't affect views attached to the Flask application afterwards – that's why having `rebar.init_app(app)` *after* `FlaskInjector` instantiation won't produce a working application.
