### ISSUE TITLE
Use instance method for url rules

### ISSUE THREAD

**Issue by ReneHollander** [alecthomas/flask_injector#34]
I am trying to add instance methods to handle different endpoints. The instance of the class itself is created by injector and will add the routes to the flask app.
Because FlaskInjector needs to be run after adding all endpoints, I also bind the Flask app during the initialization step of the app.
```python
from flask import Flask
from flask_injector import request, FlaskInjector
from injector import inject, Module, singleton, Injector


class HelloWorldServiceModule(Module):
    def configure(self, binder):
        binder.bind(HelloWorldService, scope=request)


class HelloWorldService:
    def hello_world(self, str):
        return "Hello " + str


class HelloWorldEndpointModule(Module):
    def configure(self, binder):
        binder.install(HelloWorldServiceModule)
        binder.bind(HelloWorldEndpoint, scope=singleton)


class HelloWorldEndpoint:
    @inject
    def __init__(self, app: Flask):
        self.app = app
        self.app.add_url_rule('/hello/<name>', 'hello', self.say_hello)

    def say_hello(self, name, hello_world_service: HelloWorldService):
        return hello_world_service.hello_world(name)


def start_app(clazz, modules):
    flask_app = Flask(__name__)

    def configure_flask(binder):
        binder.bind(Flask, to=flask_app, scope=singleton)

    modules.insert(0, configure_flask)
    injector = Injector(modules=modules, auto_bind=False)
    injector.get(clazz)
    FlaskInjector(app=flask_app, injector=injector)

    flask_app.run('0.0.0.0')


if __name__ == "__main__":
    start_app(HelloWorldEndpoint, [HelloWorldEndpointModule])
```

Running the app causes the following error:
```
Traceback (most recent call last):
  File "/mnt/c/Users/Rene Hollander/repositories/rep0st/flask_injector_magic.py", line 47, in <module>
    start_app(HelloWorldEndpoint, [HelloWorldEndpointModule])
  File "/mnt/c/Users/Rene Hollander/repositories/rep0st/flask_injector_magic.py", line 41, in start_app
    FlaskInjector(app=flask_app, injector=injector)
  File "/mnt/c/Users/Rene Hollander/repositories/rep0st/venv/lib/python3.6/site-packages/flask_injector.py", line 309, in __init__
    process_dict(container, injector)
  File "/mnt/c/Users/Rene Hollander/repositories/rep0st/venv/lib/python3.6/site-packages/flask_injector.py", line 337, in process_dict
    d[key] = wrap_fun(value, injector)
  File "/mnt/c/Users/Rene Hollander/repositories/rep0st/venv/lib/python3.6/site-packages/flask_injector.py", line 65, in wrap_fun
    return wrap_fun(inject(fun), injector)
  File "/mnt/c/Users/Rene Hollander/repositories/rep0st/venv/lib/python3.6/site-packages/injector/__init__.py", line 1055, in inject
    return method_wrapper(function, bindings)
  File "/mnt/c/Users/Rene Hollander/repositories/rep0st/venv/lib/python3.6/site-packages/injector/__init__.py", line 1132, in method_wrapper
    read_and_store_bindings(bindings)
  File "/mnt/c/Users/Rene Hollander/repositories/rep0st/venv/lib/python3.6/site-packages/injector/__init__.py", line 1128, in read_and_store_bindings
    f.__bindings__ = merged_bindings
AttributeError: 'method' object has no attribute '__bindings__'
```
I guess FlaskInjector just does not support instance methods at this point.

I will further investigate the issue tomorrow and maybe try to get a fix for it, hoping there is nothing obvious I am missing in regards to the issue.

**Comment by jstasiak** [comment]
Hmm, interesting, I haven't actually considered adding routes this way, hence this approach not being tested. Just so it's clear for the readers – it's bound instance methods specifically that cause troubles here.

This should not be terribly difficult to work around or fix in Flask-Injector itself. Example of a workaround:

```
def instance_method_wrapper(im):
    @functools.wraps(im)
    def wrapper(*args, **kwargs):
        return im(*args, **kwargs)

# and then:
    self.app.add_url_rule('/hello/<name>', 'hello', instance_method_wrapper(self.say_hello))
```

(Just one of many possible approaches, I'm not saying it's particularly nice but it does the job)

**Comment by ReneHollander** [comment]
Thanks, I created a pull request for the fix.

(I also replaced class with instance in my original post)
