### ISSUE TITLE
Error with error handler and typing

### ISSUE THREAD

**Issue by Sytten** [alecthomas/flask_injector#36]
Hi!
I seem to have a found a bug with the error handler and typing. Consider this code:
```python
def init_error_handlers(app: Flask) -> None:
    app.register_error_handler(SQLAlchemyError, handle_sqlalchemy_error)


def handle_sqlalchemy_error(error: SQLAlchemyError) -> Response:
    logger.error("SQLAlchemy error: %s", error)
    return _create_json_error_response(
        errors.BadRequest.default_message, errors.BadRequest.http_status_code
    )
```

If I remove the type on the error it works fine, but with the type:
```
injector.CallError: Call to handle_sqlalchemy_error(DataError('(psycopg2.DataError) invalid input syntax for type uuid: "61dc1bb7-ed81-448b-88ac-04996a0cff8"\nLINE 3: WHERE organisations.id = \'61dc1bb7-ed81-448b-88ac-04996a0cff...\n                                 ^\n'), error=SQLAlchemyError()) failed: handle_sqlalchemy_error() got multiple values for argument 'error' (injection stack: [])
```

Full Call stack:
```
Traceback (most recent call last):
  File "/Users/******/Core/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/******/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/******/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/******/venv/lib/python3.7/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/Users/******/venv/lib/python3.7/site-packages/flask_injector.py", line 76, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "/Users/******/venv/lib/python3.7/site-packages/injector/__init__.py", line 868, in call_with_injection
    reraise(e, CallError(self_, callable, args, dependencies, e, self._stack))
  File "/Users/******/venv/lib/python3.7/site-packages/injector/__init__.py", line 67, in reraise
    raise exception.with_traceback(tb)
  File "/Users/******/venv/lib/python3.7/site-packages/injector/__init__.py", line 866, in call_with_injection
    **dependencies)
```

**Comment by jstasiak** [comment]
Hmm, yes, you're right. I'll see about fixing this, for the time being you should be able to work around it by decorating `handle_sqlalchemy_error` with `@noninjectable('error')` (`noninjectable` can be imported from `injector`).

**Comment by jstasiak** [comment]
Injector 0.16.x released today should fix this (warning: the release breaks backward compatibility in some areas).

**Comment by Sytten** [comment]
I believe you mean 0.12.x just for future reference

**Comment by jstasiak** [comment]
Injector, not Flask-Injector: https://github.com/alecthomas/injector/commit/a25cd8ef27ad0e3d8e9fbe347a84985e3ff6836f

**Comment by Sytten** [comment]
Ho right!
