### ISSUE TITLE
Doing multiple requests on a flask test client on an injected route fails for all but the first request.

### ISSUE THREAD

**Issue by niax** [alecthomas/flask_injector#6]
All but the first call to the test client results in:

        Traceback (most recent call last):
          File "/home/nickh/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
                response = self.full_dispatch_request()
          File "/home/nickh/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
                rv = self.handle_user_exception(e)
          File "/home/nickh/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
                reraise(exc_type, exc_value, tb)
          File "/home/nickh/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
                rv = self.dispatch_request()
          File "/home/nickh/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
                return self.view_functions[rule.endpoint](**req.view_args)
          File "/home/nickh/env/local/lib/python2.7/site-packages/flask/views.py", line 83, in view
                self = view.view_class(*class_args, **class_kwargs)
          File "/home/nickh/env/local/lib/python2.7/site-packages/flask_injector.py", line 48, in cls
                current_class, additional_kwargs=kwargs)
          File "/home/nickh/env/local/lib/python2.7/site-packages/injector.py", line 692, in create_object
                instance = cls.__new__(cls)
        TypeError: function.__new__(X): X is not a type object (function)

This looks to be because the flask injector double-wraps the object being made.

**Comment by jstasiak** [comment]
To the best of my knowledge this is fixed so I'll close this issue. @niax please reopen if it doesn't work for you.
